### ISSUE TITLE
GraphQL version

### ISSUE THREAD

**Issue by anacicconi** [sirsavary/fastify-graphql#5]
Hello,

I just noticed you require graphql on your dependencies. Is this really necessary? I don't see where it's used in the project. I just installed the 0.13 version of graphql in my project and I had to downgrade the version in order to use your plugin.

Thanks!

**Comment by anacicconi** [comment]
Hello,

I just saw you're using graphql for your tests. Sorry for the issue. However, I wasn't able to install the plugin because of the fastify-plugin version. Someone already did a PR to fix it:

https://github.com/sirsavary/fastify-graphql/pull/7

**Comment by sirsavary** [comment]
It's a devDependencys there _shouldn't_ be an issue with it being listed. If for whatever reason installing this module brings GraphQL along with it and you're using `yarn`, use the "resolutions" section of your package.json to force a specific GraphQL version (see https://yarnpkg.com/en/docs/selective-version-resolutions).

Also, #7 has been merged. You should be good to go :)

**Comment by anacicconi** [comment]
Thanks for your reply @sirsavary !
