### ISSUE TITLE
Can I use with Graphql subscription ?

### ISSUE THREAD

**Issue by annibuliful** [sirsavary/fastify-graphql#9]

**Comment by Extarys** [comment]
```
import { SubscriptionServer } from 'subscriptions-transport-ws'
import { execute, subscribe } from 'graphql'
var httpSrv = fastify.listen(3002, err => {
	if (err) throw err;
	console.log('Server listenting on localhost:', fastify.server.address().port);
});
const graphSrv = new SubscriptionServer(
	{
		execute,
		subscribe,
		schemaGraph
	},
	{
		server: httpSrv,
		path: '/graphql'
	}
)
```

I have some schema issues, but that'S the code I have right now. Hope it works.

**Comment by annibuliful** [comment]
Thank you sir

**Comment by Extarys** [comment]
I had to change `schemaGraph` to `schema: schemaGraph` though (I forgot to change it in my first reply), hope you figured it out! :smile:

**Comment by lagmanzaza** [comment]
VS code show that variable is undefined

**Comment by annibuliful** [comment]
Thank you sir

**Comment by sirsavary** [comment]
Apologies for not seeing this sooner! Thank you @Extarys for your example, I might document this in the README.

**Comment by Extarys** [comment]
No problem, my pleasure

**Comment by annibuliful** [comment]
<img width="812" alt="screen shot 2561-05-12 at 00 03 46" src="https://user-images.githubusercontent.com/5283709/39936857-03b88f98-5578-11e8-81ae-3e6a0f25bb9b.png">
<img width="653" alt="screen shot 2561-05-12 at 00 04 29" src="https://user-images.githubusercontent.com/5283709/39936878-11bf1576-5578-11e8-8492-dd890a8ad707.png">


it doesn't work . I don't know what are the problems

**Comment by annibuliful** [comment]
I fix it by changing `httpServer` to `fastify.server` it's not error but Subscription doesn't work. Why?

**Comment by annibuliful** [comment]
<img width="1440" alt="screen shot 2561-06-03 at 05 20 48" src="https://user-images.githubusercontent.com/5283709/40881331-f25d50a8-66ed-11e8-8fa8-34a626330335.png">

I'm not sure that `[object object]` is error or not ?

**Comment by annibuliful** [comment]
https://github.com/n3ologism/music-fastify/tree/backend/backend/src

This is my repository

**Comment by nmrcs** [comment]
@lagmanzaza  tnx, its work for me `fastify.server`

```javascript
import { execute, subscribe } from 'graphql'
import { SubscriptionServer } from 'subscriptions-transport-ws';

import { schema } from "./api/schema"

const fastify = require('fastify')({
	logger: false
})

// This `listen` method launches a web-server
fastify.listen(3000, (err, address) => {
	if (err) throw err
	console.log('\x1b[35m', `🚀 Server ready at http://localhost:3000/graphql`)
	console.log("\x1b[35m", `🚀 Subscription server ws://localhost:3000/graphql`)
})

new SubscriptionServer(
	{
		schema,
		execute,
		subscribe,
	},
	{
		server: fastify.server,
		path: '/graphql',
	},
);

```

**Comment by annibuliful** [comment]
@nikitamarcius  Actually, You can use Apollo server instead

**Comment by nmrcs** [comment]
@lagmanzaza nope. Tried first, HTTP endpont works, but subscriptions no `handshake error`. Test with Koa and Fastify. Works only with HTTP native module

Better Graphql + Fastify + subscriptions.
